phone_number:
  min_length: 8
  max_length: 11
table:
  minimum_value: 1
  maximum_value: 20
capacity:
  minimum_value: 1
  maximum_value: 6
page:
  max: 9
menu:
  number_item_in_page: 6
review:
  number_item_in_page: 5
  size_box: 10x10
